* 必然

-----

粗略的看完了必然，感触是不少，尤其今天 AlphaGo 对柯洁 3:0 完胜，更是对
未来充满了期待与不安。 必然中讲到，智能分为很多种，每种心智在某一方面
更加的擅长。就围棋而言，难道我们下不过，就下定我们人类智力不如它，真的
不是。人类的优势在于感性的认识，而非精确的计算，即使人类最最顶尖的人才
也不行。从下围棋，我们就看到了，人工智能算出了尽可能多的可能，你走的每
一步，它都能看到这一步的未来，面对这样的机器，只会让人绝望。或许我们人
类真的在围棋这个高地上失守了。


** 第二章 知化 cognifying

    - 人工智能时代的到来最大的益处在于，各种人工智能将帮助我们定义人性。我们需要人工智能告诉我们——我们是谁？
    - 这不是一场人类与机器人之间的竞赛，而是一场机器人参与的竞赛。如果和机器人比赛，我们必输无疑。
    - 机器人已经低调的走进了我们的生活。不久，更张扬、更聪明的机器人必将出现。它们所带来的颠覆效果将直抵我们生活的核心。

** 第三章 流动 Flowing

    - 流动的时间同样也发生了转变，在第一阶段里，任务往往以批处理模式完
      成。每个月都会收到账单；税金总是要在每年的同一天申报--事情总是堆
      积起来等待一次完成。而在第二阶段，随着网络的到来，我们很快期待所
      有的事情能在当天完成。如今是第三阶段，我们已经从日清日毕模式转换
      到了实时模式。
    - 经济学中有一条颠扑不破的定理：一旦某样事物变得免费，变得无所不在，那么它的经济地位就会突然反转。
    - 在这个充满了免费数字复制品的超饱和数字时空中，复制品无处不在，太过廉价，以至于只有无法复制的事情才变得真正有价值。
    - 有八种“比免费更好”的原生性特性：即时性，个性化，解释性，可靠性，获取权，实体化，可赞助，可寻性。

** 第五章 使用 Accessing

    - 一个有意思的现象：“优步作为世界上最大的出租车公司，却不拥有任何
      出租车辆。脸谱网作为世界上最流行的媒体平台，却不创造任何内容。阿
      里巴巴作为最有价值的零售公司，却没有任何库存。一些有意思的事情正
      在发生。”
    - 对事物的占有不在像曾经那样重要，而对事物的使用则比以往更加重要。
    - 现代文明的每个方面都已经开始变得扁平化，除了其中一个方面-货币。
      但如果你也能将货币去中心化呢？ 如果你能创建一种分布式货币，它安
      全、准确，并且无需中央就可确保其价值，又会怎样？
    - 比特币是一种完全去中心化、分布式的货币，它无需任何一家中央银行来
      为其准确性、强制性与协调性负责。
    - 比特币最重要的创新是它的“区块链”-使其变得强大的数字化技术。作为
      一个革命性的发明，区块链能够让金钱之外的很多系统都实现去中心化。
    - 平台是提供服务的工厂，而服务则偏爱使用权胜于所有权。
    - 云端是现存机器中可靠性最高的。它们可以表现出著名的5个9的进化完美的服务。
    - 云端的一个核心优势在于，它变得越大，我们的设备就变得越小巧、越轻薄。

** 第七章 过滤 Filtering

    - 在一个信息丰富的世界，大量的信息内容意味着某种东西的缺乏：无论它
      是什么，肯定是因信息消耗引起的缺乏。而大量信息消耗的是什么，这是
      显而易见的：它消耗的是信息接受者的注意力。因此信息的丰富促成了注
      意力的缺乏。西蒙的这一见解通常被简化为：“在信息丰富的世界里，唯
      一稀缺的资源就是人类的注意力。”

** 第八章 重混 Remixing

    - 学术研究领域已经制造出一些有趣的原型机可以实现视频的总结浏览，但
      还不能广泛用于所有的电影。一些有着巨量片源可供选择的流行网站（比
      如黄色网站）已经发明了一种方式，使得用户可以花几秒钟的时间浏览整
      部电影的内容。当用户点击一个电影标题的时候时，弹出窗口就会一个接
      一个地闪现影片中的关键画面，形成一个快速播放的幻灯片，就像这部电
      影的手翻书。
    - 可视化的窍门在于可检索性，也就是说我们有能力像谷歌搜索网页一样检
      索所有的电影，并找到某个具体镜头。

** 第九章 互动 Interacting

    - 虚拟现实的技术亮点不仅仅是“存在感”，另一个让它经久不衰的魅力源于
      它的互动效果。
    - 设备和我们的互动程度越高，口碑就越好，而我们的体验也会更棒。
    - 人们偏爱交互式的产品，而苹果是第一家意思到这一点的公司。
    - 关于数字讨论都掩盖了一个关于人类的事实：我们的数学直觉很差。人类
      的大脑不擅长统计。数学不是我们天生的语言。

** 第十章 追踪 Tracking

    - 量变将引起质变。如果一种东西的数量足够多，那么它很可能表现出少量
      单一个体所不具备的属性。

** 第十一章 提问 Questioning

    - 讽刺的是，在全球即时联通的时代，我对任何事情的把握反而变弱了。相
      比于从专家那里得到的事实，我更愿意从网络上流动的事实中拼凑出自己
      认为正确的事实。
    - 我注意到蜂巢式的心智已经将我的思考方式充分地推广并散布开来。我的
      思考方式更偏向行动而不是沉思。当出现一个疑惑或一种直觉，我不会在
      内心反复咀嚼，让自己的无知不断滋养它。我会开始做事，会迅速行动。
      我开始寻找、搜索、提问、质疑、突然行动、记笔记、做标记，尝试把一
      切变为自己的东西。我不会等待，也无需等待。有了一个想法后我会先行
      动而不是先思考。
